services:
  php:
    build:
      context: docker/php
    restart: always
    expose:
      - ${PHP_PORT}
    working_dir: ${APP_PATH}
    user: ${UID}:${GID}
    volumes:
      - ${SOURCE_PATH}:${APP_PATH}
    depends_on:
      - db
    links:
      - db:${MYSQL_HOST}

  composer:
    build:
      context: docker/composer
    entrypoint: composer
    working_dir: ${APP_PATH}
    user: ${UID}:${GID}
    volumes:
      - ${SOURCE_PATH}:${APP_PATH}

  nginx:
    image: nginx:1.27.4
    command: /bin/bash -c "envsubst '$$NGINX_PORT $$NGINX_ROOT $$PHP_HOST $$PHP_PORT' < /etc/nginx/site.conf.tmpl > /etc/nginx/sites-available/site.conf && nginx -g 'daemon off;'"
    restart: always
    ports: 
      - ${NGINX_PORT}:${NGINX_PORT}
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - NGINX_ROOT=${APP_PATH}
      - PHP_HOST=${PHP_HOST}
      - PHP_PORT=${PHP_PORT}
    depends_on:
      - php
    links:
      - php:${PHP_HOST}
    volumes:
      - ${SOURCE_PATH}:${APP_PATH}:ro
      - /etc/nginx/sites-available
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/site.conf.tmpl:/etc/nginx/site.conf.tmpl:ro

  db:
    image: mysql:9.2.0
    restart: always
    expose:
      - ${MYSQL_PORT}
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql

volumes:
  db: